### ISSUE TITLE
Please Enable TestingHelpers to throw Exceptions

### ISSUE THREAD

**Issue by Rainer1** [System-IO-Abstractions/System.IO.Abstractions#442] opened 2019-01-21 15:35 UTC
It quite some scenarios it is necessary to ensure by UnitTests, that the written code handles Exceptions correctly which are thrown by the file system.
For this reason it would be great to be able to define a Exception to be thrown, when a specific Method Is called.
Example Similar to many Mocking Frameworks:
`MockFileSystem.File.Delete.WhenCalled( (file) => throw new IOException(message))`

**Comment by fgreinacher** [comment] 2019-03-09 12:56
Duplicate of #168 - consider leaving your thumbs up there to show support :)

**Closed by fgreinacher** 2019-03-09 12:56 UTC
