### ISSUE TITLE
File.Delete(string path) throw exception  - cannot access file because it is being used by another process.

### ISSUE THREAD

**Issue by Phil1iu** [System-IO-Abstractions/System.IO.Abstractions#689] opened 2020-12-22 03:07 UTC
**File.Delete(string path) throw exception while file size more than 66KB - cannot access file because it is being used by another process.**

**To Reproduce**
1. Create a file named Test.SVG (path: ‪C:\Test.SVG) which size larger than 66KB.
2. Invoke method to delete it if exists
        if (File.Exist("C:\\Test.SVG"))
        {
            File.Delete("C:\\Test.SVG")
        }
3. Fail to delete the Test.SVG file
4. See error - System.IO.IOException: The process cannot access the file 'C:\Test.svg' because it is being used by another process.

**Expected behavior**
The file can be deleted without any errors. 

**Additional context**
It can be deleted successfully if file size is less than 66KB, or I added code "Thread.Sleep(100)" before File.Delete("C:\\Test.SVG"). 

System.IO.Abstractions  version : 12.2.7

**Comment by fgreinacher** [comment] 2020-12-22 16:21
Do you experience the same when using `System.IO` directly? We just forward calls there, see e.g. https://github.com/System-IO-Abstractions/System.IO.Abstractions/blob/d8f5d322cd9d5b542f2b4caca170bdabb9f05a15/src/System.IO.Abstractions/FileWrapper.cs#L90

**Comment by Phil1iu** [comment] 2020-12-23 01:20
Yes, tried to use System.IO directly, same error happened as I mentioned. OK, it seems something wrong System.IO

**Comment by fgreinacher** [comment] 2020-12-23 12:55
OK, then it's probably best to file an issue in the [.NET runtime repository](https://github.com/dotnet/runtime). 

I'll close this issue, when you found  the root cause feel free to share it here 👍

**Closed by fgreinacher** 2020-12-23 12:56 UTC
Labels: area: core, state: needs discussion, type: bug
