### ISSUE TITLE
Building fails on Xamarin.iOS

### ISSUE THREAD

**Issue by Cheesebaron** [System-IO-Abstractions/System.IO.Abstractions#634] opened 2020-08-05 11:32 UTC
**Describe the bug**
Version 12.1.1 Fails linking on Xamarin.iOS during builds. Not sure when this started, but just updated from 7.1.1, which has worked fine.

```
 MTOUCH : error MT2101: Can't resolve the reference 'System.Void System.IO.FileSystemAclExtensions::Create(System.IO.DirectoryInfo,System.Security.AccessControl.DirectorySecurity)', referenced from the method 'System.Void System.IO.Abstractions.DirectoryInfoWrapper::Create(System.Security.AccessControl.DirectorySecurity)' in 'System.IO.FileSystem.AccessControl, Version=4.0.5.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. [/Users/runner/work/1/s/TrackMan.DrivingRangeApp.iOS/TrackMan.DrivingRangeApp.iOS.csproj]
```

Also, explicitly tried to add a package reference to System.IO.FileSystem.AccessControl, which doesn't change anything.

**To Reproduce**
Add `System.IO.Abstractions` as package ref in a Xamarin.iOS project, build it in release mode.

**Expected behavior**
Build should pass

**Additional context**

**Comment by fgreinacher** [comment] 2020-08-08 18:55
Weird, I don't really know much about Xamarin, but https://github.com/xamarin/xamarin-macios/issues/8028 looks like exactly the same problem (they even mention `System.IO.Abstractions` over there 🤖).

I'll ask for an update from the Xamarin maintainers, maybe they have an idea.

**Comment by dannythomas13** [comment] 2020-08-10 12:54
I too am facing this issue, thought adding reference directly to iOS project may help but still fails

**Comment by fgreinacher** [comment] 2020-08-10 20:23
@Cheesebaron @dannythomas13 Do you have a repo that shows the problem? Did you try the workarounds mentioned in https://github.com/xamarin/xamarin-macios/issues/8028#issuecomment-671283527?

**Comment by Cheesebaron** [comment] 2020-08-11 06:23
@fgreinacher going to try out adding `<RestoreProjectStyle>PackageReference</RestoreProjectStyle>` and see if that helps

**Comment by Cheesebaron** [comment] 2020-08-11 06:30
Yeah, that didn't help at all. Will make a sample project.

**Comment by Cheesebaron** [comment] 2020-08-11 07:00
Here it is: https://github.com/Cheesebaron/sys-io-abstraction-build-fail

**Comment by fgreinacher** [comment] 2020-08-11 15:14
Thanks for the repro! Would be awesome if you could try using the dev builds as mentioned in https://github.com/xamarin/xamarin-macios/issues/8028#issuecomment-671946028 and give feedback here. 🤝

**Comment by dannythomas13** [comment] 2020-08-19 10:41
@Cheesebaron @fgreinacher Is there any update on this?

**Comment by Cheesebaron** [comment] 2020-08-19 19:35
I haven't tested it yet, I don't want to pollute my machine with preview versions of mono/xamarin.ios.

**Comment by krzysztofstepnikowski** [comment] 2020-09-09 15:43
Hello Guys,
Did you resolve this problem? I've got the same issue only on the Release mode. I tried to reinstall Visual Studio for Mac, update a Xcode or SDK but it didn't resolve.
Please let me know if anyone finds solution.

**Comment by fgreinacher** [comment] 2020-09-09 18:38
I don't have the environment to test this at the moment, sorry. Could try the dev builds mentioned in https://github.com/System-IO-Abstractions/System.IO.Abstractions/issues/634#issuecomment-672007212?

**Comment by krzysztofstepnikowski** [comment] 2020-09-09 18:49
Ok, or I will install previous version like 7.1.1.

**Comment by krzysztofstepnikowski** [comment] 2020-09-09 18:55
@Cheesebaron Tomasz, you mentioned that you've updated from 7.1.1. Is there not this issue right? I have to relase an application, but I need this library, so I'm looking for stable version and I want to make a sure.

**Comment by dannythomas13** [comment] 2020-09-09 19:31
Sorry to say that for our release we had to downgrade to 7.0.15, fingers crossed we can upgrade to a future version

**Comment by krzysztofstepnikowski** [comment] 2020-09-09 19:43
> Sorry to say that for our release we had to downgrade to 7.0.15, fingers crossed we can upgrade to a future version

Ok, thanks, so this version doesn't have this problem right?

**Comment by fgreinacher** [comment] 2020-10-12 20:53
According to https://github.com/xamarin/xamarin-macios/issues/8028#issuecomment-706102911 the issue will be fixed in Xamarin.iOS `d16-9`. Unfortunately it seems we cannot do anything but waiting for this update, so I'll close this issue...

**Closed by fgreinacher** 2020-10-12 20:53 UTC
Labels: state: needs discussion, type: bug

**Comment by janduldhardt** [comment] 2022-06-16 08:32
Did anyone find a solution to this? Makes testing very difficult without this interface in Xamarin.ios

**Comment by fgreinacher** [comment] 2022-06-16 11:37
Does this still occur with current Xamarin versions? I was assuming this has been fixed when I closed the issue.

**Comment by fgreinacher** [comment] 2022-06-20 11:10
Ah thanks. Looking at [the last comment](https://github.com/xamarin/xamarin-macios/issues/10884#issuecomment-1125786846) in the issue you linked the Xamarin folks need a project to reproduce the problem.

So the next step would be to do this. I have zero experience with Xamarin, so I need someone else to do it.

Feel free to `@` my in the Xamarin tracker whenever we can change something in SIOA to make this work.
